import * as THREE from 'three';
import { COLORS, MAIN_HALL_DIMS } from '../utils/constants.js';
export function createMainHall(scene) {
  const { WIDTH, DEPTH, HEIGHT } = MAIN_HALL_DIMS;
  const interactables = [];
  const floor = new THREE.Mesh(new THREE.PlaneGeometry(WIDTH, DEPTH), new THREE.MeshStandardMaterial({ color: 0x1a1a1a, roughness: 0.15, metalness: 0.1 }));
  floor.rotation.x = -Math.PI/2; floor.receiveShadow = true; scene.add(floor);
  const rf = new THREE.Mesh(new THREE.PlaneGeometry(WIDTH, DEPTH), new THREE.MeshStandardMaterial({ color: 0x111111, roughness: 0.05, metalness: 0.3, transparent: true, opacity: 0.15 }));
  rf.rotation.x = -Math.PI/2; rf.position.y = 0.001; scene.add(rf);
  const g = new THREE.GridHelper(WIDTH, 30, 0x1a1a22, 0x111116); g.position.y = 0.005; g.material.opacity = 0.12; g.material.transparent = true; scene.add(g);
  const ceil = new THREE.Mesh(new THREE.PlaneGeometry(WIDTH, DEPTH), new THREE.MeshStandardMaterial({ color: 0x0d0d0d, roughness: 0.8 }));
  ceil.rotation.x = Math.PI/2; ceil.position.y = HEIGHT; scene.add(ceil);
  const wM = new THREE.MeshStandardMaterial({ color: 0x121218, roughness: 0.6, metalness: 0.05 });
  const aM = new THREE.MeshStandardMaterial({ color: 0x0f0f14, roughness: 0.5, metalness: 0.02 });
  const bw = new THREE.Mesh(new THREE.BoxGeometry(WIDTH, HEIGHT, 0.3), aM); bw.position.set(0, HEIGHT/2, -DEPTH/2); bw.receiveShadow = true; scene.add(bw);
  const fw = new THREE.Mesh(new THREE.BoxGeometry(WIDTH, HEIGHT, 0.3), wM); fw.position.set(0, HEIGHT/2, DEPTH/2); scene.add(fw);
  [-WIDTH/2, WIDTH/2].forEach(x => { const w = new THREE.Mesh(new THREE.BoxGeometry(0.3, HEIGHT, DEPTH), wM); w.position.set(x, HEIGHT/2, 0); w.receiveShadow = true; scene.add(w); });
  const cG = new THREE.CylinderGeometry(0.3, 0.35, HEIGHT, 16), cM = new THREE.MeshStandardMaterial({ color: 0x1a1a20, roughness: 0.3, metalness: 0.15 });
  const rG = new THREE.TorusGeometry(0.38, 0.03, 8, 24), rM = new THREE.MeshStandardMaterial({ color: COLORS.SET_GOLD, roughness: 0.2, metalness: 0.9 });
  [[-10,-6],[-10,6],[10,-6],[10,6],[-5,-6],[-5,6],[5,-6],[5,6]].forEach(([x,z]) => {
    const c = new THREE.Mesh(cG, cM); c.position.set(x, HEIGHT/2, z); c.castShadow = true; scene.add(c);
    const r = new THREE.Mesh(rG, rM); r.rotation.x = Math.PI/2; r.position.set(x, 0.1, z); scene.add(r);
    const t = r.clone(); t.position.set(x, HEIGHT-0.1, z); scene.add(t);
  });
  const fM = new THREE.MeshStandardMaterial({ color: COLORS.SET_GOLD, roughness: 0.3, metalness: 0.85 });
  [-9,-3,3,9].forEach((x,i) => {
    scene.add(Object.assign(new THREE.Mesh(new THREE.BoxGeometry(3.5, 2.5, 0.15), fM), { position: new THREE.Vector3(x, 3.5, -DEPTH/2+0.25), castShadow: true }));
    const cv = new THREE.Mesh(new THREE.PlaneGeometry(3.0, 2.0), new THREE.MeshStandardMaterial({ color: new THREE.Color().setHSL(i*0.2+0.05, 0.4, 0.25), roughness: 0.7 }));
    cv.position.set(x, 3.5, -DEPTH/2+0.35); cv.userData = { type: 'painting', name: 'Painting '+(i+1), description: 'Original artwork by Chris Marchese.', interactive: true };
    scene.add(cv); interactables.push(cv);
  });
  const sofa = new THREE.MeshStandardMaterial({ color: 0x0a0a0a, roughness: 0.85 });
  const s1 = new THREE.Mesh(new THREE.BoxGeometry(4, 0.5, 1.5), sofa); s1.position.set(8, 0.4, 4); s1.castShadow = true; scene.add(s1);
  scene.add(Object.assign(new THREE.Mesh(new THREE.BoxGeometry(4, 0.8, 0.3), sofa), { position: new THREE.Vector3(8, 0.9, 4.75) }));
  const s2m = new THREE.Mesh(new THREE.BoxGeometry(3, 0.5, 1.5), sofa); s2m.position.set(10.5, 0.4, 1.5); s2m.rotation.y = -Math.PI/2; scene.add(s2m);
  scene.add(Object.assign(new THREE.Mesh(new THREE.BoxGeometry(1.8, 0.05, 1), new THREE.MeshStandardMaterial({ color: COLORS.SET_GOLD, roughness: 0.25, metalness: 0.8 })), { position: new THREE.Vector3(8, 0.55, 2.5) }));
  const bg = new THREE.Group(); bg.position.set(-12, 0, 7);
  const bM = new THREE.MeshStandardMaterial({ color: COLORS.PHONE_RED, roughness: 0.5, metalness: 0.1 });
  const bb = new THREE.Mesh(new THREE.BoxGeometry(1.2, 2.8, 1.2), bM); bb.position.y = 1.4; bb.castShadow = true; bg.add(bb);
  bg.add(Object.assign(new THREE.Mesh(new THREE.BoxGeometry(1.4, 0.15, 1.4), bM), { position: new THREE.Vector3(0, 2.85, 0) }));
  bg.add(Object.assign(new THREE.Mesh(new THREE.BoxGeometry(0.6, 0.3, 0.6), bM), { position: new THREE.Vector3(0, 3.1, 0) }));
  const bl = new THREE.PointLight(0xFFAA44, 1.5, 5); bl.position.y = 2.2; bg.add(bl);
  bb.userData = { type: 'phonebooth', name: 'Contact Chris', description: 'Pick up the phone to reach Chris Marchese.', interactive: true };
  scene.add(bg); interactables.push(bb);
  const sM = new THREE.MeshStandardMaterial({ color: COLORS.CHROME_SILVER, roughness: 0.2, metalness: 0.7 });
  const pG = new THREE.CylinderGeometry(0.5, 0.55, 1.2, 16), pM = new THREE.MeshStandardMaterial({ color: 0x1a1a20, roughness: 0.4 });
  const tk = new THREE.Mesh(new THREE.TorusKnotGeometry(0.6, 0.15, 100, 16, 2, 3), sM); tk.position.set(-3, 1.8, 3); tk.castShadow = true; scene.add(tk);
  scene.add(Object.assign(new THREE.Mesh(pG, pM), { position: new THREE.Vector3(-3, 0.6, 3) }));
  const ic = new THREE.Mesh(new THREE.IcosahedronGeometry(0.7, 0), new THREE.MeshStandardMaterial({ color: COLORS.SET_GOLD, roughness: 0.25, metalness: 0.9 }));
  ic.position.set(3, 1.8, 5); ic.castShadow = true; ic.userData.animate = (t) => { ic.rotation.y = t*0.3; ic.rotation.x = Math.sin(t*0.5)*0.1; }; scene.add(ic);
  scene.add(Object.assign(new THREE.Mesh(pG, pM), { position: new THREE.Vector3(3, 0.6, 5) }));
  const dd = new THREE.Mesh(new THREE.DodecahedronGeometry(0.5, 0), sM); dd.position.set(-7, 1.6, -2); dd.castShadow = true;
  dd.userData.animate = (t) => { dd.rotation.y = -t*0.2; }; scene.add(dd);
  scene.add(Object.assign(new THREE.Mesh(pG, pM), { position: new THREE.Vector3(-7, 0.5, -2) }));
  const em = new THREE.Mesh(new THREE.RingGeometry(2, 2.2, 48), new THREE.MeshStandardMaterial({ color: COLORS.SET_GOLD, roughness: 0.3, metalness: 0.8, transparent: true, opacity: 0.15 }));
  em.rotation.x = -Math.PI/2; em.position.y = 0.01; scene.add(em);
  return { interactables };
}