import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { COLORS, MAIN_HALL_DIMS, PLAYER, PILLAR_POSITIONS, ROOMS } from './utils/constants.js';
import { createMainHall } from './rooms/MainHall.js';
import { createLightPillar } from './effects/LightPillar.js';
import { createCharacter } from './character/Character.js';
import { setupInteractions } from './controls/Interactions.js';
const st={currentRoom:ROOMS.MAIN_HALL,isLoaded:false,isStarted:false,keys:{w:false,a:false,s:false,d:false,shift:false},character:null,interactables:[],clock:new THREE.Clock()};
const scene=new THREE.Scene();scene.background=new THREE.Color(COLORS.DEEP_BLACK);scene.fog=new THREE.FogExp2(COLORS.DEEP_BLACK,0.018);
const camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,0.1,200);camera.position.set(0,PLAYER.CAMERA_OFFSET.y,PLAYER.CAMERA_OFFSET.z+5);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});
renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;renderer.outputColorSpace=THREE.SRGBColorSpace;
document.getElementById('app').appendChild(renderer.domElement);
const oc=new OrbitControls(camera,renderer.domElement);oc.enableDamping=true;oc.dampingFactor=0.08;oc.minDistance=3;oc.maxDistance=12;oc.maxPolarAngle=Math.PI*0.48;oc.minPolarAngle=Math.PI*0.15;oc.enablePan=false;oc.enabled=false;
function setupLighting(){scene.add(new THREE.AmbientLight(0x1a1a2e,0.4));const k=new THREE.DirectionalLight(0xFFF4E0,0.8);k.position.set(5,12,3);k.castShadow=true;k.shadow.mapSize.set(2048,2048);k.shadow.camera.near=0.5;k.shadow.camera.far=50;k.shadow.camera.left=-20;k.shadow.camera.right=20;k.shadow.camera.top=15;k.shadow.camera.bottom=-15;k.shadow.bias=-0.0001;scene.add(k);scene.add(Object.assign(new THREE.DirectionalLight(0x8899BB,0.3),{position:new THREE.Vector3(-5,8,-3)}));const r1=new THREE.PointLight(0xC5A55A,0.6,20);r1.position.set(-12,6,-8);scene.add(r1);const r2=new THREE.PointLight(0x4466AA,0.4,20);r2.position.set(12,6,8);scene.add(r2);for(let i=0;i<4;i++){const s=new THREE.SpotLight(0xFFF0D4,1.5,15,Math.PI/8,0.5,1.5);s.position.set(-10+i*6,7,-9.5);s.target.position.set(-10+i*6,1.5,-9.8);s.castShadow=true;s.shadow.mapSize.set(512,512);scene.add(s);scene.add(s.target);}}
const lb=document.getElementById('loading-bar'),lp=document.getElementById('loading-percent'),ls=document.getElementById('loading-screen'),so=document.getElementById('start-overlay');
let pr=0;const sl=()=>{const iv=setInterval(()=>{pr+=Math.random()*12+3;if(pr>=100){pr=100;clearInterval(iv);setTimeout(()=>{ls.classList.add('hidden');so.classList.remove('hidden');st.isLoaded=true;},600);}lb.style.width=pr+'%';lp.textContent=Math.floor(pr);},180);};
async function init(){setupLighting();const h=createMainHall(scene);st.interactables.push(...h.interactables);const cp=createLightPillar(scene,PILLAR_POSITIONS.CAPITAL,COLORS.CAPITAL_GOLD,'Capital Portal',ROOMS.CAPITAL);const ip=createLightPillar(scene,PILLAR_POSITIONS.INFRASTRUCTURE,COLORS.INFRA_BLUE,'Infrastructure Portal',ROOMS.INFRASTRUCTURE);const gp=createLightPillar(scene,PILLAR_POSITIONS.GROWTH,COLORS.GROWTH_GREEN,'Growth Portal',ROOMS.GROWTH);st.interactables.push(cp.hitbox,ip.hitbox,gp.hitbox);st.character=createCharacter(scene);oc.target.copy(st.character.position);oc.target.y=PLAYER.CAMERA_LOOK_OFFSET.y;setupInteractions(camera,st.interactables,st.character);sl();}
so.addEventListener('click',()=>{so.classList.add('hidden');oc.enabled=true;document.getElementById('crosshair').style.display='block';const r=document.getElementById('room-label');r.textContent='MAIN HALL';r.classList.add('visible');setTimeout(()=>r.classList.remove('visible'),3000);st.isStarted=true;});
addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(k in st.keys)st.keys[k]=true;if(k==='shift')st.keys.shift=true;});
addEventListener('keyup',e=>{const k=e.key.toLowerCase();if(k in st.keys)st.keys[k]=false;if(k==='shift')st.keys.shift=false;});
function upd(dt){if(!st.isStarted||!st.character)return;const spd=PLAYER.SPEED*(st.keys.shift?PLAYER.SPRINT_MULTIPLIER:1)*dt;const dir=new THREE.Vector3();const fw=new THREE.Vector3();camera.getWorldDirection(fw);fw.y=0;fw.normalize();const rt=new THREE.Vector3();rt.crossVectors(fw,new THREE.Vector3(0,1,0)).normalize();if(st.keys.w)dir.add(fw);if(st.keys.s)dir.sub(fw);if(st.keys.d)dir.add(rt);if(st.keys.a)dir.sub(rt);if(dir.length()>0){dir.normalize();const np=st.character.position.clone().add(dir.multiplyScalar(spd));const hw=MAIN_HALL_DIMS.WIDTH/2-PLAYER.RADIUS-0.5,hd=MAIN_HALL_DIMS.DEPTH/2-PLAYER.RADIUS-0.5;np.x=Math.max(-hw,Math.min(hw,np.x));np.z=Math.max(-hd,Math.min(hd,np.z));st.character.position.copy(np);st.character.rotation.y=THREE.MathUtils.lerp(st.character.rotation.y,Math.atan2(dir.x,dir.z),0.15);st.character.position.y=Math.sin(st.clock.getElapsedTime()*8)*0.03;}else{st.character.position.y=Math.sin(st.clock.getElapsedTime()*1.5)*0.01;}oc.target.lerp(new THREE.Vector3(st.character.position.x,st.character.position.y+PLAYER.CAMERA_LOOK_OFFSET.y,st.character.position.z),0.1);}
function animate(){requestAnimationFrame(animate);const dt=Math.min(st.clock.getDelta(),0.05);upd(dt);oc.update();scene.traverse(c=>{if(c.userData&&c.userData.animate)c.userData.animate(st.clock.getElapsedTime());});renderer.render(scene,camera);}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});
init();animate();