import*as T from'three';import{OrbitControls}from'three/addons/controls/OrbitControls.js';import{COLORS,MAIN_HALL_DIMS as D,PLAYER as P,PILLAR_POSITIONS as PP,ROOMS}from'./utils/constants.js';import{createMainHall}from'./rooms/MainHall.js';import{createLightPillar}from'./effects/LightPillar.js';import{createCharacter}from'./character/Character.js';import{setupInteractions}from'./controls/Interactions.js';
const s={room:ROOMS.MAIN_HALL,go:false,keys:{w:0,a:0,s:0,d:0,shift:0},ch:null,ia:[],ck:new T.Clock()};
const sc=new T.Scene();sc.background=new T.Color(COLORS.DEEP_BLACK);sc.fog=new T.FogExp2(COLORS.DEEP_BLACK,.018);
const cam=new T.PerspectiveCamera(55,innerWidth/innerHeight,.1,200);cam.position.set(0,P.CAMERA_OFFSET.y,P.CAMERA_OFFSET.z+5);
const rr=new T.WebGLRenderer({antialias:1,powerPreference:'high-performance'});rr.setSize(innerWidth,innerHeight);rr.setPixelRatio(Math.min(devicePixelRatio,2));rr.shadowMap.enabled=1;rr.shadowMap.type=T.PCFSoftShadowMap;rr.toneMapping=T.ACESFilmicToneMapping;rr.toneMappingExposure=1.2;rr.outputColorSpace=T.SRGBColorSpace;document.getElementById('app').appendChild(rr.domElement);
const oc=new OrbitControls(cam,rr.domElement);oc.enableDamping=1;oc.dampingFactor=.08;oc.minDistance=3;oc.maxDistance=12;oc.maxPolarAngle=Math.PI*.48;oc.minPolarAngle=Math.PI*.15;oc.enablePan=0;oc.enabled=0;
function light(){sc.add(new T.AmbientLight(0x1a1a2e,.4));const k=new T.DirectionalLight(0xFFF4E0,.8);k.position.set(5,12,3);k.castShadow=1;k.shadow.mapSize.set(2048,2048);k.shadow.camera.near=.5;k.shadow.camera.far=50;k.shadow.camera.left=-20;k.shadow.camera.right=20;k.shadow.camera.top=15;k.shadow.camera.bottom=-15;k.shadow.bias=-.0001;sc.add(k);sc.add(Object.assign(new T.DirectionalLight(0x8899BB,.3),{position:new T.Vector3(-5,8,-3)}));sc.add(Object.assign(new T.PointLight(0xC5A55A,.6,20),{position:new T.Vector3(-12,6,-8)}));sc.add(Object.assign(new T.PointLight(0x4466AA,.4,20),{position:new T.Vector3(12,6,8)}));for(let i=0;i<4;i++){const sp=new T.SpotLight(0xFFF0D4,1.5,15,Math.PI/8,.5,1.5);sp.position.set(-10+i*6,7,-9.5);sp.target.position.set(-10+i*6,1.5,-9.8);sp.castShadow=1;sp.shadow.mapSize.set(512,512);sc.add(sp);sc.add(sp.target);}}
let pg=0;function sl(){const iv=setInterval(()=>{pg+=Math.random()*12+3;if(pg>=100){pg=100;clearInterval(iv);setTimeout(()=>{document.getElementById('loading-screen').classList.add('hidden');document.getElementById('start-overlay').classList.remove('hidden');},600);}document.getElementById('loading-bar').style.width=pg+'%';document.getElementById('loading-percent').textContent=Math.floor(pg);},180);}
function init(){light();const h=createMainHall(sc);s.ia.push(...h.interactables);[['CAPITAL',COLORS.CAPITAL_GOLD,'Capital Portal'],['INFRASTRUCTURE',COLORS.INFRA_BLUE,'Infrastructure Portal'],['GROWTH',COLORS.GROWTH_GREEN,'Growth Portal']].forEach(([k,c,l])=>{const p=createLightPillar(sc,PP[k],c,l,ROOMS[k]);s.ia.push(p.hitbox);});s.ch=createCharacter(sc);oc.target.copy(s.ch.position);oc.target.y=P.CAMERA_LOOK_OFFSET.y;setupInteractions(cam,s.ia,s.ch);sl();}
document.getElementById('start-overlay').onclick=()=>{document.getElementById('start-overlay').classList.add('hidden');oc.enabled=1;document.getElementById('crosshair').style.display='block';const rl=document.getElementById('room-label');rl.textContent='MAIN HALL';rl.classList.add('visible');setTimeout(()=>rl.classList.remove('visible'),3e3);s.go=1;};
onkeydown=e=>{const k=e.key.toLowerCase();if(k in s.keys)s.keys[k]=1;if(k==='shift')s.keys.shift=1;};onkeyup=e=>{const k=e.key.toLowerCase();if(k in s.keys)s.keys[k]=0;if(k==='shift')s.keys.shift=0;};
function mv(dt){if(!s.go||!s.ch)return;const sp=P.SPEED*(s.keys.shift?P.SPRINT_MULTIPLIER:1)*dt,dir=new T.Vector3(),fw=new T.Vector3();cam.getWorldDirection(fw);fw.y=0;fw.normalize();const rt=new T.Vector3();rt.crossVectors(fw,new T.Vector3(0,1,0)).normalize();if(s.keys.w)dir.add(fw);if(s.keys.s)dir.sub(fw);if(s.keys.d)dir.add(rt);if(s.keys.a)dir.sub(rt);if(dir.length()>0){dir.normalize();const n=s.ch.position.clone().add(dir.multiplyScalar(sp)),hw=D.WIDTH/2-P.RADIUS-.5,hd=D.DEPTH/2-P.RADIUS-.5;n.x=Math.max(-hw,Math.min(hw,n.x));n.z=Math.max(-hd,Math.min(hd,n.z));s.ch.position.copy(n);s.ch.rotation.y=T.MathUtils.lerp(s.ch.rotation.y,Math.atan2(dir.x,dir.z),.15);s.ch.position.y=Math.sin(s.ck.getElapsedTime()*8)*.03;}else s.ch.position.y=Math.sin(s.ck.getElapsedTime()*1.5)*.01;oc.target.lerp(new T.Vector3(s.ch.position.x,s.ch.position.y+P.CAMERA_LOOK_OFFSET.y,s.ch.position.z),.1);}
!function a(){requestAnimationFrame(a);const dt=Math.min(s.ck.getDelta(),.05);mv(dt);oc.update();sc.traverse(c=>{if(c.userData?.animate)c.userData.animate(s.ck.getElapsedTime());});rr.render(sc,cam);}();
onresize=()=>{cam.aspect=innerWidth/innerHeight;cam.updateProjectionMatrix();rr.setSize(innerWidth,innerHeight);};init();